### ISSUE TITLE
Amend specification to include more information about the relationship with Link header and/or links in response bodies like HAL or other formats.

### ISSUE THREAD

**Issue by evert** [evert/push-please#7]

**Comment by hibaymj** [comment]
I don't think you want to dive into content parsing here. If it ever needs to get done, the right tool for the job should be used from the RDF world.

**Comment by evert** [comment]
Not really suggesting that anyone should do content-parsing. The idea here is that (for example) HAL or HTML-based API's have a syntax for defining links. Implementors of the Prefer-Push header shouldn't be forced to move links into headers. The goal is of this ticket really is to say: this specification doesn't care about where links appear and this could be different depending on the media-type.
